version: '3.4'

services:
  api-gateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - catalog-service
      - order-service

  catalog-service:
    image: catalogservice
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - "5001:80"

  order-service:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5002:80"
